admin:
  email: admin@admin.com
  password: "admin123.."
  nickname: "admin"
  user_id : "10000"

system:
  ssl: false # 是否启用ssl true的话不会使用port
  gateway_address: "127.0.0.1"
  gateway_port: 8080
  jwt_secret: "secret"

email:
  enable: false
  smtp_server: "smtp.qq.com"
  port: 25
  username: "2318266924@qq.com"
  password: "zjnudhwoiuknecgh"

http:
  name: "admin_bff"
  address: "0.0.0.0"
  port: 8087

register:
  address: "consul"   # 注册中心地址
  port: 8500            # 注册中心端口
  tags: ["admin", "bff", "管理服务"]

log:
  stdout: true
  level: -1
  file: "logs/app.log"
  format: "console" # console、json

mysql:
  address: "mysql"
  port: 33306
  username: "root"
  password: "888888"
  database: "coss"
  opts:
    allowNativePasswords: "true"
    timeout: "800ms"
    readTimeout: "200ms"
    writeTimeout: "800ms"
    parseTime: "true"
    loc: "Local"
    charset: "utf8mb4"

redis:
  proto: "tcp"
  address: "redis"
  port: 6379
  password: "Hitosea@123.."
#  protocol: 3

dtm:
  name: "dtm"
  address: "dtm"
  port: 36790

message_queue:
  name: "rabbitmq"
  username: "root"
  password: "Hitosea@123.."
  address: "rabbitmq"
  port: 5672

oss:
  name: "minio"
  address: "minio"
  port: 9000
  accessKey: "root"
  secretKey: "Hitosea@123.."
  ssl: false
  presignedExpires: ""
  dial: "3000ms"
  timeout: "5000ms"

discovers:
  user:
    name: "user_service"
    address: "user_service"
    port: 10002
    direct: true
  relation:
    name: "relation_service"
    address: "relation_service"
    port: 10001
    direct: true
  msg:
    name: "msg_service"
    address: "msg_service"
    port: 10000
    direct: true
  push:
    name: "push_service"
    address: "push_service"
    port: 10007
    direct: true