definitions:
  dto.CallOption:
    properties:
      audio_enabled:
        description: 是否启用音频
        type: boolean
      codec:
        description: 编解码器
        type: string
      frame_rate:
        description: 帧率
        type: integer
      resolution:
        description: 分辨率
        type: string
      video_enabled:
        description: 是否启用视频
        type: boolean
    type: object
  dto.ParticipantInfo:
    properties:
      identity:
        description: 用户昵称
        type: string
      is_publisher:
        description: 创建者
        type: boolean
      joined_at:
        description: 加入时间
        type: integer
      name:
        type: string
      sid:
        description: 房间id
        type: string
      state:
        allOf:
        - $ref: '#/definitions/dto.ParticipantState'
        description: 用户状态
    type: object
  dto.ParticipantState:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      ParticipantInfo_ACTIVE: 双方都已加入通话
      ParticipantInfo_DISCONNECTED: 断开连接
      ParticipantInfo_JOINED: 已加入通话，对方未响应
      ParticipantInfo_JOINING: websocket已连接，未加入通话
    x-enum-varnames:
    - ParticipantInfo_JOINING
    - ParticipantInfo_JOINED
    - ParticipantInfo_ACTIVE
    - ParticipantInfo_DISCONNECTED
  dto.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  dto.UserCallRequest:
    properties:
      option:
        $ref: '#/definitions/dto.CallOption'
      user_id:
        description: 接收视频通话的用户ID
        type: string
    required:
    - user_id
    type: object
  dto.UserCallResponse:
    properties:
      room:
        description: 房间名称
        type: string
      room_id:
        description: 房间id
        type: string
      token:
        description: 加入通话的token
        type: string
      url:
        description: webRtc服务器地址
        type: string
    type: object
  dto.UserJoinRequest:
    properties:
      option:
        $ref: '#/definitions/dto.CallOption'
      room:
        description: 房间名称
        type: string
    required:
    - room
    type: object
  dto.UserLeaveRequest:
    properties:
      room:
        description: 房间名称
        type: string
    required:
    - room
    type: object
  dto.UserRejectRequest:
    properties:
      room:
        description: 房间名称
        type: string
    required:
    - room
    type: object
  dto.UserShowResponse:
    properties:
      duration:
        description: 房间持续时间
        type: integer
      participant:
        items:
          $ref: '#/definitions/dto.ParticipantInfo'
        type: array
      room:
        description: 房间名称
        type: string
      start_at:
        description: 创建房间时间
        type: integer
      video_call_record_url:
        type: string
      video_call_status:
        type: string
    type: object
info:
  contact: {}
  title: Swagger Example API
paths:
  /live/user/create:
    post:
      consumes:
      - application/json
      description: 创建用户通话
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserCallRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserCallResponse'
              type: object
      security:
      - Bearer: []
      summary: 创建用户通话
      tags:
      - liveUser
  /live/user/join:
    post:
      consumes:
      - application/json
      description: 加入通话
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserJoinRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: 加入通话
      tags:
      - liveUser
  /live/user/leave:
    post:
      consumes:
      - application/json
      description: 结束通话
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserLeaveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: 结束通话
      tags:
      - liveUser
  /live/user/reject:
    post:
      consumes:
      - application/json
      description: 拒绝通话
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRejectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: 拒绝通话
      tags:
      - liveUser
  /live/user/show:
    get:
      description: 获取通话房间信息
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: 房间名
        in: query
        name: room
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: participant=通话参与者
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserShowResponse'
              type: object
      security:
      - Bearer: []
      summary: 获取通话房间信息
      tags:
      - liveUser
swagger: "2.0"
