definitions:
  model.EditGroupMsgRequest:
    properties:
      content:
        description: New content of the message
        type: string
      msg_id:
        description: Message ID
        type: integer
      msg_type:
        type: integer
    required:
    - content
    - msg_id
    - msg_type
    type: object
  model.EditUserMsgRequest:
    properties:
      content:
        description: 消息内容
        type: string
      msg_id:
        description: Message ID
        type: integer
      msg_type:
        description: 消息类型
        type: integer
    required:
    - content
    - msg_id
    - msg_type
    type: object
  model.RecallGroupMsgRequest:
    properties:
      msg_id:
        description: Message ID
        type: integer
    required:
    - msg_id
    type: object
  model.RecallUserMsgRequest:
    properties:
      msg_id:
        description: Message ID
        type: integer
    required:
    - msg_id
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.SendGroupMsgRequest:
    properties:
      content:
        type: string
      dialog_id:
        type: integer
      group_id:
        type: integer
      replay_id:
        type: integer
      type:
        type: integer
    required:
    - content
    - dialog_id
    - group_id
    - type
    type: object
  model.SendUserMsgRequest:
    properties:
      content:
        type: string
      dialog_id:
        type: integer
      receiver_id:
        type: string
      replay_id:
        type: integer
      type:
        type: integer
    required:
    - content
    - dialog_id
    - receiver_id
    - type
    type: object
info:
  contact: {}
  title: Swagger Example API
paths:
  /msg/dialog/list:
    get:
      consumes:
      - application/json
      description: 获取用户对话列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户对话列表
  /msg/edit/group:
    post:
      consumes:
      - application/json
      description: 编辑群消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.EditGroupMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 编辑群消息
  /msg/edit/user:
    post:
      consumes:
      - application/json
      description: 编辑用户消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.EditUserMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 编辑用户消息
  /msg/list/user:
    get:
      consumes:
      - application/json
      description: 获取私聊消息
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 类型
        in: query
        name: type
        required: true
        type: string
      - description: 消息
        in: query
        name: content
        type: string
      - description: 页码
        in: query
        name: page_num
        type: integer
      - description: 页大小
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取私聊消息
  /msg/recall/group:
    post:
      consumes:
      - application/json
      description: 撤回群消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RecallGroupMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 撤回群消息
  /msg/recall/user:
    post:
      consumes:
      - application/json
      description: 撤回用户消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RecallUserMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 撤回用户消息
  /msg/send/group:
    post:
      consumes:
      - application/json
      description: 发送群聊消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendGroupMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 发送群聊消息
  /msg/send/user:
    post:
      consumes:
      - application/json
      description: 发送私聊消息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendUserMsgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 发送私聊消息
  /msg/ws:
    get:
      description: websocket请求
      responses: {}
      summary: websocket请求
swagger: "2.0"
