definitions:
  model.ActionEnum:
    enum:
    - 0
    - 1
    type: integer
    x-enum-comments:
      ActionAccepted: 同意
      ActionRejected: 拒绝
    x-enum-varnames:
    - ActionRejected
    - ActionAccepted
  model.AddBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  model.AdminManageJoinGroupRequest:
    properties:
      action:
        $ref: '#/definitions/model.ActionEnum'
      group_id:
        type: integer
      user_id:
        type: string
    required:
    - group_id
    - user_id
    type: object
  model.DeleteBlacklistRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  model.DeleteFriendRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  model.GroupRequestListResponse:
    properties:
      creator_id:
        type: string
      group_avatar:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      group_status:
        type: integer
      group_type:
        type: integer
      max_members_limit:
        type: integer
      msg:
        type: string
      user_avatar:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  model.InviteGroupRequest:
    properties:
      group_id:
        type: integer
      member:
        items:
          type: string
        type: array
    required:
    - group_id
    - member
    type: object
  model.JoinGroupRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  model.ManageFriendRequest:
    properties:
      action:
        $ref: '#/definitions/model.ActionEnum'
      e2e_public_key:
        type: string
      request_id:
        type: integer
    required:
    - request_id
    type: object
  model.ManageJoinGroupRequest:
    properties:
      action:
        $ref: '#/definitions/model.ActionEnum'
      group_id:
        type: integer
      inviter_id:
        type: string
    required:
    - group_id
    type: object
  model.QuitGroupRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  model.RemoveUserFromGroupRequest:
    properties:
      group_id:
        type: integer
      user_id:
        type: string
    required:
    - group_id
    - user_id
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.SendFriendRequest:
    properties:
      remark:
        type: string
      user_id:
        type: string
    required:
    - user_id
    type: object
  model.SetGroupSilentNotificationRequest:
    properties:
      group_id:
        description: 群ID
        type: integer
      is_silent:
        allOf:
        - $ref: '#/definitions/model.SilentNotificationType'
        description: 是否开启静默通知
    required:
    - group_id
    type: object
  model.SetUserSilentNotificationRequest:
    properties:
      is_silent:
        allOf:
        - $ref: '#/definitions/model.SilentNotificationType'
        description: 是否开启静默通知
      user_id:
        description: 用户ID
        type: string
    required:
    - user_id
    type: object
  model.SilentNotificationType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-comments:
      IsSilent: 开启静默通知
      NotSilent: 静默通知关闭
    x-enum-varnames:
    - NotSilent
    - IsSilent
  model.SwitchUserE2EPublicKeyRequest:
    properties:
      public_key:
        type: string
      user_id:
        type: string
    required:
    - public_key
    - user_id
    type: object
  model.UserInfo:
    properties:
      user_avatar:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  model.UserRequestListResponse:
    properties:
      id:
        type: integer
      receiver_id:
        type: string
      receiver_info:
        $ref: '#/definitions/model.UserInfo'
      remark:
        type: string
      request_at:
        type: integer
      sender_id:
        type: string
      sender_info:
        $ref: '#/definitions/model.UserInfo'
      user_status:
        type: integer
    type: object
  usersorter.CustomGroupData:
    properties:
      avatar:
        type: string
      dialog_id:
        type: integer
      group_id:
        type: integer
      name:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  title: coss-relation-bff服务
paths:
  /relation/delete_blacklist:
    post:
      consumes:
      - application/json
      description: 删除黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.DeleteBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 删除黑名单
      tags:
      - UserRelation
  /relation/group/admin/manage/join:
    post:
      consumes:
      - application/json
      description: 管理员管理加入群聊 action (0=拒绝, 1=同意)
      parameters:
      - description: 'Action (0: rejected, 1: joined)'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AdminManageJoinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 管理员管理加入群聊
      tags:
      - GroupRelation
  /relation/group/admin/manage/remove:
    post:
      consumes:
      - application/json
      description: 将用户从群聊移除
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RemoveUserFromGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 将用户从群聊移除
      tags:
      - GroupRelation
  /relation/group/invite:
    post:
      consumes:
      - application/json
      description: 邀请加入群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.InviteGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 邀请加入群聊
      tags:
      - GroupRelation
  /relation/group/join:
    post:
      consumes:
      - application/json
      description: 加入群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.JoinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 加入群聊
      tags:
      - GroupRelation
  /relation/group/list:
    get:
      description: 群聊列表
      produces:
      - application/json
      responses:
        "200":
          description: status 0:正常状态；1:被封禁状态；2:被删除状态
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/usersorter.CustomGroupData'
                  type: array
              type: object
      summary: 群聊列表
      tags:
      - GroupRelation
  /relation/group/manage_join:
    post:
      consumes:
      - application/json
      description: 用户管理加入群聊 action (0=拒绝, 1=同意)
      parameters:
      - description: 'Action (0: rejected, 1: joined)'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ManageJoinGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户管理加入群聊
      tags:
      - GroupRelation
  /relation/group/member:
    get:
      description: 群聊成员列表
      parameters:
      - description: 群聊ID
        in: query
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 群聊成员列表
      tags:
      - GroupRelation
  /relation/group/quit:
    post:
      consumes:
      - application/json
      description: 退出群聊
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.QuitGroupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 退出群聊
      tags:
      - GroupRelation
  /relation/group/request_list:
    get:
      consumes:
      - application/json
      description: 获取用户的群聊申请列表
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: status (0=申请中, 1=待通过, 2=已加入, 3=已删除, 4=被拒绝, 5=被封禁)
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.GroupRequestListResponse'
              type: object
      security:
      - Bearer: []
      summary: 获取群聊申请列表
      tags:
      - GroupRelation
  /relation/group/silent:
    post:
      consumes:
      - application/json
      description: 设置群聊静默通知
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetGroupSilentNotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 设置群聊静默通知
      tags:
      - GroupRelation
  /relation/user/add_blacklist:
    post:
      consumes:
      - application/json
      description: 添加黑名单
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddBlacklistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 添加黑名单
      tags:
      - UserRelation
  /relation/user/add_friend:
    post:
      consumes:
      - application/json
      description: 发送好友请求
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 发送好友请求
      tags:
      - UserRelation
  /relation/user/blacklist:
    get:
      description: 黑名单
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 黑名单
      tags:
      - UserRelation
  /relation/user/delete_friend:
    post:
      consumes:
      - application/json
      description: 删除好友
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.DeleteFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 删除好友
      tags:
      - UserRelation
  /relation/user/friend_list:
    get:
      description: 好友列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 好友列表
      tags:
      - UserRelation
  /relation/user/manage_friend:
    post:
      consumes:
      - application/json
      description: 管理好友请求  action (0=拒绝, 1=同意)
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ManageFriendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 管理好友请求
      tags:
      - UserRelation
  /relation/user/request_list:
    get:
      description: 好友申请列表
      produces:
      - application/json
      responses:
        "200":
          description: UserStatus 申请状态 (0=申请中, 1=待通过, 2=已添加, 3=被拒绝, 4=已删除, 5=已拒绝)
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.UserRequestListResponse'
                  type: array
              type: object
      summary: 好友申请列表
      tags:
      - UserRelation
  /relation/user/silent:
    post:
      consumes:
      - application/json
      description: 设置私聊静默通知
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetUserSilentNotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 设置私聊静默通知
      tags:
      - UserRelation
  /relation/user/switch/e2e/key:
    post:
      consumes:
      - application/json
      description: 交换用户端到端公钥
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SwitchUserE2EPublicKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerToken: []
      summary: 交换用户端到端公钥
      tags:
      - UserRelation
swagger: "2.0"
