definitions:
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.ModifyUserSecretBundleRequest:
    properties:
      secret_bundle:
        type: string
    required:
    - secret_bundle
    type: object
  model.PasswordRequest:
    properties:
      confirm_password:
        type: string
      old_password:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - old_password
    - password
    type: object
  model.RegisterRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      public_key:
        type: string
    required:
    - confirm_password
    - email
    - password
    - public_key
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.SetPublicKeyRequest:
    properties:
      public_key:
        type: string
    required:
    - public_key
    type: object
  model.UserInfoRequest:
    properties:
      avatar:
        type: string
      nickname:
        type: string
      signature:
        type: string
      tel:
        type: string
    type: object
info:
  contact: {}
  title: coss-user服务
paths:
  /user/bundle/get:
    get:
      consumes:
      - application/json
      description: 获取用户密钥包
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取用户密钥包
  /user/bundle/modify:
    post:
      consumes:
      - application/json
      description: 修改用户密码
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ModifyUserSecretBundleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerToken: []
      summary: 修改用户密钥包
  /user/info:
    get:
      consumes:
      - application/json
      description: 查询用户信息
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 指定根据id还是邮箱类型查找
        enum:
        - 0
        - 1
        in: query
        name: type
        required: true
        type: integer
      - description: 邮箱
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 查询用户信息
  /user/info/modify:
    post:
      consumes:
      - application/json
      description: 修改用户信息
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerToken: []
      summary: 修改用户信息
  /user/key/set:
    post:
      consumes:
      - application/json
      description: 设置用户公钥
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SetPublicKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerToken: []
      summary: 设置用户公钥
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户登录
  /user/logout:
    post:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 退出登录
  /user/password/modify:
    post:
      consumes:
      - application/json
      description: 修改用户密码
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.PasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerToken: []
      summary: 修改用户密码
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户注册
  /user/system/key/get:
    get:
      consumes:
      - application/json
      description: 获取系统pgp公钥
      parameters:
      - description: 指定根据id还是邮箱类型查找
        enum:
        - 0
        - 1
        in: query
        name: type
        required: true
        type: integer
      - description: 邮箱
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 获取系统pgp公钥
swagger: "2.0"
